envVarGroups:
  - name: clickhouse-credentials
    envVars:
      - key: CLICKHOUSE_USER
        value: dittofeed
      - key: CLICKHOUSE_PASSWORD
        generateValue: true
  - name: backend-app-env
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLICKHOUSE_PROTOCOL
        value: http
      - key: DASHBOARD_URL_NAME
        value: RENDER_EXTERNAL_URL
      - key: DASHBOARD_API_NAME
        value: RENDER_EXTERNAL_URL
      - key: DASHBOARD_API_DOMAIN
        value: onrender.com
      - key: DASHBOARD_API_PORT
        value: 443
      - key: LITE_MEM_LIMIT
        value: 412
  - name: temporal-shared
    envVars:
    - key: DYNAMIC_CONFIG_FILE_PATH
      value: /etc/temporal/dynamicconfig.yaml
    - key: DB
      value: postgresql
services:
  - type: web
    name: dittofeed-lite
    runtime: docker
    dockerfilePath: packages/lite/Dockerfile
    dockerContext: .
    autoDeploy: false
    # Setting Node.js max-old-space-size to 412 MB.
    # This is calculated as follows: Total RAM (512 MB) - Buffer (100 MB) -
    # Memory for other processes (100 MB).
    dockerCommand: node --max-old-space-size=412 packages/lite/dist/scripts/startLite.js --workspace-name=$WORKSPACE_NAME
    envVars:
      - fromGroup: backend-app-env
      - fromGroup: clickhouse-credentials
      - key: WORKSPACE_NAME
        sync: false
      - key: REUSE_CONTEXT
        value: "true"
      - key: MAX_CACHED_WORKFLOWS
        value: "10"
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_kJYiLFes9V0Q@ep-fragrant-heart-aiy9uam6-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require
      - key: CLICKHOUSE_HOST
        fromService:
          type: pserv
          name: dittofeed-ch
          property: host
      - key: TEMPORAL_ADDRESS
        fromService:
          type: pserv
          name: temporal
          property: host
      - key: PASSWORD
        sync: false
      - key: SECRET_KEY
        generateValue: true
      # comment out bootstrap env var after initial setup
      - key: BOOTSTRAP
        value: "true"
  - type: worker
    name: admin-cli
    runtime: docker
    dockerfilePath: packages/admin-cli/Dockerfile
    dockerContext: .
    autoDeploy: false
    dockerCommand: tail -f /dev/null
    envVars:
      - fromGroup: backend-app-env
      - fromGroup: clickhouse-credentials
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_kJYiLFes9V0Q@ep-fragrant-heart-aiy9uam6-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require
      - key: CLICKHOUSE_HOST
        fromService:
          type: pserv
          name: dittofeed-ch
          property: host
      - key: TEMPORAL_ADDRESS
        fromService:
          type: pserv
          name: temporal
          property: host
  - type: pserv
    name: dittofeed-ch
    env: docker
    plan: standard
    autoDeploy: false
    dockerfilePath: render/clickhouse/Dockerfile
    dockerContext: .
    envVars:
      - fromGroup: backend-app-env
      - fromGroup: clickhouse-credentials
    disk:
      name: data
      mountPath: /var/lib/clickhouse
      sizeGB: 10
  - type: pserv
    name: temporal
    autoDeploy: false
    env: docker
    dockerfilePath: render/temporal/server/auto-setup/Dockerfile
    dockerContext: .
    envVars:
    - fromGroup: temporal-shared
    - key: PORT
      value: 7233
    - key: DBNAME
      value: neondb
    - key: DB_PORT
      value: "5432"
    - key: POSTGRES_USER
      value: neondb_owner
    - key: POSTGRES_PWD
      value: npg_kJYiLFes9V0Q
    - key: POSTGRES_SEEDS
      value: ep-fragrant-heart-aiy9uam6-pooler.c-4.us-east-1.aws.neon.tech
